score_threshold: 0.1
range: 70
width: 672
height: 672
use_intensity_feature: true
use_constant_feature: false
z_offset: -1.7
engine_file: data/vlp-16.engine
prototxt_file: data/vlp-16.prototxt
caffemodel_file: data/vlp-16.caffemodel